name: Run Component Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをクローン
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js を設定
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 環境変数を .env ファイルとして保存
      - name: Set environment variables
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env

      # 依存関係をインストール
      - name: Install dependencies
        run: npm install

      # テストを実行
      - name: Run tests
        run: npm test -- --watchAll=false
